# Redes neuronales convolucionales
con Tensorflow y Keras 

### Aprendizaje de neuronas

Entrenar una sola neurona para hacer una prediccion

En este problema se construlle un perceptron simple como el propuesto por McCulloch & Pitts. usando la funcion Sigmoide

### Planteamiento del problema

Queremos mostrarle a una neurona simple un conjunto de ejemplos para qye pueda aprender como se comporta una funcion. El conjunto de ejemplos es el siguiente

- `(1, 0)` deberia devolver `1`
- `(0, 1)` deberia devolver `1`
- `(0, 0)` deberia devolver `0`

Entonces, si ingresamos a la neurona el valor de `(1, 1)` deberia poder predecir el numero `1`

### Que necesitamos hacer?

Programar y entrenar la neurona para hacer predicciones.

- Construir la clase y su constructor
- Definir la funcion sigmoide y su derivada
- Definir el numero de epocas para el entrenamiento
- Resolver el probmea y predecir el valor de la salida deseada

In [1]:
import numpy as np

class sigmoid_neuron():

    def __init__(self, n =2):
        '''Constructor of the class'''
        np.random.seed(1)
        self.synaptic_weights = 2 * np.random.random((n, 1)) - 1 # La neurona devuelve pesos entre -1, 1

    def __sigmoid(self, x):
        '''Sigmoid function'''
        return 1. / (1. + np.exp(- x))

    def __sigmoid_derivative(self, x):
        '''Derivative of the Sigmoid function'''
        return x * (1 - x)

    def train(self, training_inputs, training_output, iterations):
        '''Training function'''
        for iteration in range(iterations):
            output = self.predict(training_inputs)
            error = training_output.reshape((len(training_inputs), 1)) - output
            adjustment = np.dot(training_inputs.T, error * self.__sigmoid_derivative(output))
            self.synaptic_weights += adjustment

    def predict(self, inputs):
        '''Prediction function'''

        return self.__sigmoid(np.dot(inputs, self.synaptic_weights))

### Generando las muestras
Ahora se puede guardar la lista de ejemplos basados en la descripcion del problema

In [2]:
# Ejemplos de entrenamiento
input_values = [(1, 0), (0, 1), (0, 0)]
output_values = [1, 1, 0]

training_inputs = np.array(input_values)
trainig_outputs = np.array(output_values).T.reshape((3, 1))

In [3]:
# revision de valores
training_inputs

array([[1, 0],
       [0, 1],
       [0, 0]])

In [4]:
# Revision de valores
trainig_outputs

array([[1],
       [1],
       [0]])

### Entrenando la neurona

Para hacer el entrenamiento, primero definiremos una neurona. De forma predeterminada, contendra pesos aleatorios ( por que aun no se ha entrenado)

In [5]:
# Inicializando la neurona sigmoide
neuron = sigmoid_neuron(2)
print('Pesos iniciales aleatorios: ')
neuron.synaptic_weights

Pesos iniciales aleatorios: 


array([[-0.16595599],
       [ 0.44064899]])

#### Epocas de entrenamiento

In [18]:
# Modificamos el numero de epocas para verificar como funciona
epochs = 1_000_000

# Entrenamos la neurona con el numero de epocas
neuron.train(training_inputs, trainig_outputs, epochs)
print('Nuevos pesos sinapticos depsues de entrenamiento: ')
neuron.synaptic_weights


Nuevos pesos sinapticos depsues de entrenamiento: 


array([[7.80409127],
       [7.80409213]])

### Predicciones


In [19]:
# Predecimos para verificar el rendimiento
uno_uno = np.array((1, 1))
print('Predicciones para (1, 1): ')
neuron.predict(uno_uno)

Predicciones para (1, 1): 


array([0.99999983])